services:
  slurm:
    build:
      context: .
      args:
        SLURM_VERSION: ${SLURM_VERSION:-25.11.2}
    image: slurm-docker:${SLURM_VERSION:-25.11.2}
    hostname: slurmctl
    container_name: slurm
    init: true
    privileged: true
    environment:
      MYSQL_USER: ${MYSQL_USER:-slurm}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
    volumes:
      - var_lib_mysql:/var/lib/mysql
      - var_log_slurm:/var/log/slurm
      - slurm_data:/data
    ports:
      - "6820:6820"
      - "2222:22"

volumes:
  var_lib_mysql:
  var_log_slurm:
  slurm_data:
